# Generated by Django 5.2.4 on 2025-07-27 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_study_time', models.IntegerField(default=0, help_text='Total study time in minutes')),
                ('sessions_count', models.IntegerField(default=0)),
                ('average_session_duration', models.FloatField(default=0.0)),
                ('focus_score', models.FloatField(default=0.0, help_text='Average focus rating')),
                ('mood_score', models.FloatField(default=0.0, help_text='Average mood rating')),
                ('productivity_score', models.FloatField(default=0.0, help_text='Calculated productivity score')),
                ('subjects_studied', models.JSONField(default=list, help_text='List of subjects studied')),
                ('subject_time_breakdown', models.JSONField(default=dict, help_text='Time spent per subject')),
                ('insights', models.JSONField(default=dict, help_text='AI-generated insights for the day')),
                ('recommendations', models.JSONField(default=list, help_text='AI recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'study_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('goal_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=20)),
                ('target_study_time', models.IntegerField(help_text='Target study time in minutes')),
                ('target_sessions', models.IntegerField(default=1, help_text='Target number of sessions')),
                ('target_progress', models.FloatField(default=0.0, help_text='Target progress percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_study_time', models.IntegerField(default=0)),
                ('current_sessions', models.IntegerField(default=0)),
                ('current_progress', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'study_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('session_type', models.CharField(choices=[('course_study', 'Course Study'), ('quiz_practice', 'Quiz Practice'), ('content_review', 'Content Review'), ('project_work', 'Project Work'), ('reading', 'Reading'), ('video_watching', 'Video Watching'), ('other', 'Other')], max_length=20)),
                ('content_id', models.CharField(blank=True, help_text='ID of specific content being studied', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in minutes')),
                ('topics_covered', models.JSONField(default=list, help_text='List of topics covered')),
                ('progress_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('mood_rating', models.IntegerField(blank=True, help_text='Mood rating from 1-10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('focus_rating', models.IntegerField(blank=True, help_text='Focus rating from 1-10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('ai_insights', models.JSONField(default=dict, help_text='AI-generated insights about the session')),
                ('recommendations', models.JSONField(default=list, help_text='AI recommendations for future sessions')),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'study_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
