# Generated by Django 5.2.4 on 2025-08-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyanalytics',
            name='subjects_studied',
        ),
        migrations.RemoveField(
            model_name='studyanalytics',
            name='subject_time_breakdown',
        ),
    ]


