# Generated by Django 5.2.4 on 2025-07-27 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_explanations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexplanation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_explanations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentanalysis',
            name='explanation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='ai_explanations.aiexplanation'),
        ),
        migrations.AddField(
            model_name='explanationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanation_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='explanationhistory',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_explanations.explanationtemplate'),
        ),
    ]
