# Generated by Django 5.2.4 on 2025-08-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_explanations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexplanation',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the content'),
        ),
    ]
