# Generated by Django 5.2.4 on 2025-07-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('subject', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('estimated_duration', models.IntegerField(help_text='Estimated duration in hours')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('current_step', models.IntegerField(default=0)),
                ('ai_recommendations', models.JSONField(default=list, help_text='AI-generated course recommendations')),
                ('user_preferences', models.JSONField(default=dict, help_text='User preferences used for path generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'learning_paths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in minutes')),
                ('score', models.FloatField(blank=True, help_text='Score if applicable', null=True)),
                ('notes', models.TextField(blank=True)),
                ('study_date', models.DateTimeField(auto_now_add=True)),
                ('session_duration', models.IntegerField(default=0, help_text='Session duration in minutes')),
            ],
            options={
                'db_table': 'learning_path_progress',
                'ordering': ['-study_date'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('step_type', models.CharField(choices=[('course', 'Course'), ('quiz', 'Quiz'), ('project', 'Project'), ('assessment', 'Assessment')], max_length=20)),
                ('content_id', models.CharField(blank=True, help_text='ID of quiz, project, or assessment', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.IntegerField(help_text='Estimated duration in minutes')),
                ('prerequisites', models.JSONField(default=list, help_text='List of prerequisite step IDs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_path_steps',
                'ordering': ['order'],
            },
        ),
    ]
