# Generated by Django 5.2.4 on 2025-07-27 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('study_time', models.IntegerField(default=0, help_text='Study time in minutes')),
                ('sessions_count', models.IntegerField(default=0)),
                ('courses_accessed', models.IntegerField(default=0)),
                ('quizzes_taken', models.IntegerField(default=0)),
                ('average_quiz_score', models.FloatField(default=0.0)),
                ('focus_score', models.FloatField(default=0.0)),
                ('productivity_score', models.FloatField(default=0.0)),
                ('preferred_subjects', models.JSONField(default=list, help_text='Most studied subjects')),
                ('study_times', models.JSONField(default=list, help_text='Study session times')),
                ('learning_methods', models.JSONField(default=list, help_text='Learning methods used')),
                ('insights', models.JSONField(default=dict, help_text='AI-generated insights')),
                ('recommendations', models.JSONField(default=list, help_text='AI recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LearningStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_study_days', models.IntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('study_dates', models.JSONField(default=list, help_text='List of study dates')),
                ('milestones_achieved', models.JSONField(default=list, help_text='List of achieved milestones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_streaks',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in minutes')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('quiz_scores', models.JSONField(default=list, help_text='List of quiz scores')),
                ('average_quiz_score', models.FloatField(default=0.0)),
                ('total_quizzes_taken', models.IntegerField(default=0)),
                ('strengths', models.JSONField(default=list, help_text='List of strong topics')),
                ('weaknesses', models.JSONField(default=list, help_text='List of weak topics')),
                ('ai_recommendations', models.JSONField(default=list, help_text='AI-generated recommendations')),
                ('learning_patterns', models.JSONField(default=dict, help_text='Identified learning patterns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'progress',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('courses_enrolled', models.IntegerField(default=0)),
                ('courses_completed', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0, help_text='Total time in minutes')),
                ('average_score', models.FloatField(default=0.0)),
                ('topics_covered', models.JSONField(default=list, help_text='List of topics covered')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('preferred_learning_methods', models.JSONField(default=list, help_text='Preferred learning methods')),
                ('study_patterns', models.JSONField(default=dict, help_text='Study patterns for this subject')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subject_progress',
                'ordering': ['-updated_at'],
            },
        ),
    ]
