# Generated by Django 4.2.7 on 2025-08-17 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("progress", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("completion", "Course Completion"),
                            ("score", "Quiz Score"),
                            ("time", "Study Time"),
                            ("streak", "Learning Streak"),
                            ("custom", "Custom Goal"),
                        ],
                        default="completion",
                        max_length=20,
                    ),
                ),
                (
                    "target_value",
                    models.CharField(
                        help_text="Target value (e.g., 100%, 90 minutes)",
                        max_length=100,
                    ),
                ),
                (
                    "current_value",
                    models.CharField(
                        default="0", help_text="Current progress value", max_length=100
                    ),
                ),
                ("deadline", models.DateField()),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("hard", "Hard"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "learning_goals",
                "ordering": ["-created_at"],
            },
        ),
    ]
