# Generated by Django 5.2.4 on 2025-08-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_learninggoal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectProgress',
        ),
        migrations.RemoveField(
            model_name='learninganalytics',
            name='preferred_subjects',
        ),
    ]


